export const ActionTypes = {
  LOAD_APPLICATIONS: 'LOAD_APPLICATIONS',
  ADD_APPLICATION: 'ADD_APPLICATION',
  SWITCH_APPLICATION: 'SWITCH_APPLICATION',
  EDIT_APPLICATION:'EDIT_APPLICATION',
  LOAD_PAGES: 'LOAD_PAGES',
  ADD_PAGE: 'ADD_PAGE',
  RENAME_PAGE: 'RENAME_PAGE',
  REMOVE_PAGE: 'REMOVE_PAGE',
  EDIT_PAGE: 'EDIT_PAGE',
  LOAD_MENU: 'LOAD_MENU',
  ADD_MENU: 'ADD_MENU',
  EDIT_MENU: 'EDIT_MENU',
  REMOVE_MENU: 'REMOVE_MENU',
  LOAD_CURRENT_DOCUMENT: 'LOAD_CURRENT_DOCUMENT',
  LOAD_CURRENT_CONFIGURATION: 'LOAD_CURRENT_CONFIGURATION',
  SAVE_CURRENT_CONFIGURATION: 'SAVE_CURRENT_CONFIGURATION',
  UPDATE_CURRENT_RECORD: 'UPDATE_CURRENT_RECORD'
}
